'use strict';

// Builds dist/VideoConverter.exe -- a single file that needs nothing installed
// on the target machine.
//
// Node's SEA (single executable application) works by appending a blob to a
// copy of the node binary. The blob holds one bundled script plus any assets,
// so the local modules are inlined into one file first and public/ is carried
// along as SEA assets.
//
// Run with: npm run build

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const HERE = __dirname;
const DIST = path.join(HERE, 'dist');
const BUILD = path.join(HERE, '.build');

const LOCAL_MODULES = ['server', 'convert', 'ffmpeg', 'picker'];

function step(message) {
  console.log('  ' + message);
}

function fail(message) {
  console.error('\nBuild failed: ' + message + '\n');
  process.exit(1);
}

function run(cmd, args, opts = {}) {
  // No shell by default: on Windows a shell re-splits the command on spaces, so
  // an interpreter under "C:\Program Files" turns into "C:\Program" not found.
  // Only npx needs one, because it is a .cmd rather than a real executable.
  const r = spawnSync(cmd, args, {
    encoding: 'utf8',
    windowsHide: true,
    ...opts,
  });
  if (r.error) fail(`${cmd} could not be run: ${r.error.message}`);
  if (r.status !== 0) {
    fail(`${cmd} exited with code ${r.status}\n${(r.stderr || r.stdout || '').trim()}`);
  }
  return r.stdout || '';
}

/**
 * Inline the local requires into one script.
 *
 * Each module becomes a factory in a tiny registry, and require() is shadowed
 * so a local name hits the registry while everything else falls through to the
 * real require for node: builtins. This is enough for a handful of modules with
 * no npm dependencies, and avoids adding a bundler to the toolchain.
 */
function bundle() {
  const parts = [];
  parts.push('// Generated by build.js -- do not edit.');
  parts.push('"use strict";');
  parts.push('const __mods = {};');
  parts.push('const __cache = {};');
  parts.push('const __nodeRequire = require;');
  parts.push('function __localRequire(name) {');
  parts.push('  const key = String(name).replace(/^\\.\\//, "").replace(/\\.js$/, "");');
  parts.push('  if (!(key in __mods)) return __nodeRequire(name);');
  parts.push('  if (!(key in __cache)) {');
  parts.push('    const module = { exports: {} };');
  parts.push('    __cache[key] = module.exports;');
  parts.push('    __mods[key](module, module.exports, __localRequire);');
  parts.push('    __cache[key] = module.exports;');
  parts.push('  }');
  parts.push('  return __cache[key];');
  parts.push('}');

  for (const name of LOCAL_MODULES) {
    const source = fs.readFileSync(path.join(HERE, name + '.js'), 'utf8');
    parts.push(`__mods[${JSON.stringify(name)}] = function (module, exports, require) {`);
    parts.push(source);
    parts.push('};');
  }

  const mainSource = fs.readFileSync(path.join(HERE, 'main.js'), 'utf8');
  parts.push('(function (require) {');
  parts.push(mainSource);
  parts.push('})(__localRequire);');

  return parts.join('\n');
}

/**
 * Find a Node binary built for the other macOS architecture.
 *
 * Homebrew keeps the two prefixes apart -- /opt/homebrew for arm64 and
 * /usr/local for x86_64 -- so the counterpart is usually just the other prefix.
 * `file` confirms the architecture rather than trusting the location, since a
 * user can install either build anywhere.
 */
function findOtherArchNode(wantArch) {
  const candidates = [
    wantArch === 'x64' ? '/usr/local/bin/node' : '/opt/homebrew/bin/node',
    wantArch === 'x64' ? '/usr/local/opt/node/bin/node' : '/opt/homebrew/opt/node/bin/node',
  ];
  const marker = wantArch === 'x64' ? 'x86_64' : 'arm64';

  for (const candidate of candidates) {
    if (!fs.existsSync(candidate)) continue;
    const described = spawnSync('file', ['-b', candidate], { encoding: 'utf8' });
    if ((described.stdout || '').includes(marker)) return candidate;
  }
  return null;
}

function collectAssets() {
  const publicDir = path.join(HERE, 'public');
  const assets = {};
  for (const name of fs.readdirSync(publicDir)) {
    const full = path.join(publicDir, name);
    if (fs.statSync(full).isFile()) {
      assets[name] = full;
    }
  }
  return assets;
}

console.log('\nBuilding Video Converter\n');

// --- 1. bundle --------------------------------------------------------------

fs.rmSync(BUILD, { recursive: true, force: true });
fs.mkdirSync(BUILD, { recursive: true });
fs.mkdirSync(DIST, { recursive: true });

step('Bundling sources...');
const bundlePath = path.join(BUILD, 'bundle.js');
fs.writeFileSync(bundlePath, bundle());

// A syntax error here would otherwise only surface when the finished .exe is
// run, which is a slow way to find a typo.
const check = spawnSync(process.execPath, ['--check', bundlePath], { encoding: 'utf8' });
if (check.status !== 0) fail('bundle has a syntax error:\n' + check.stderr);

// --- 2. sea config ----------------------------------------------------------

step('Writing SEA config...');
const configPath = path.join(BUILD, 'sea-config.json');
fs.writeFileSync(
  configPath,
  JSON.stringify(
    {
      main: bundlePath,
      output: path.join(BUILD, 'sea-prep.blob'),
      disableExperimentalSEAWarning: true,
      assets: collectAssets(),
    },
    null,
    2
  )
);

// --- 3. blob ----------------------------------------------------------------

step('Generating SEA blob...');
run(process.execPath, ['--experimental-sea-config', configPath]);

// --- 4. copy the node binary ------------------------------------------------

const exeName = process.platform === 'win32' ? 'VideoConverter.exe' : 'VideoConverter';
const exePath = path.join(DIST, exeName);
const wantUniversal = process.argv.includes('--universal');

step('Copying the Node runtime...');
fs.copyFileSync(process.execPath, exePath);

// On macOS the copied runtime carries the build host's architecture, and an
// arm64 binary simply will not launch on an Intel Mac. Merging an x64 Node into
// the same file produces a universal binary that runs natively on both.
if (process.platform === 'darwin' && wantUniversal) {
  step('Building a universal binary...');
  const other = findOtherArchNode(process.arch === 'arm64' ? 'x64' : 'arm64');
  if (!other) {
    fail(
      'could not find a Node build for the other architecture.\n' +
      'Install one and try again, for example:\n' +
      '  arch -x86_64 /usr/local/bin/node --version   (Intel Node via Rosetta)\n' +
      'or drop the --universal flag to build for this machine only.'
    );
  }
  step(`  merging with ${other}`);
  const merged = path.join(BUILD, 'node-universal');
  run('lipo', ['-create', '-output', merged, process.execPath, other]);
  fs.copyFileSync(merged, exePath);
}

// Both platforms refuse to run a binary whose embedded signature no longer
// matches its contents, and injecting the blob invalidates it. The signature
// has to be removed before injection and, on macOS, re-applied afterwards.
if (process.platform === 'win32') {
  // signtool ships with the Windows SDK and is frequently absent. That is not
  // fatal: the copied node.exe is usually unsigned to begin with.
  const strip = spawnSync('signtool', ['remove', '/s', exePath], {
    encoding: 'utf8',
    windowsHide: true,
    shell: true,
  });
  if (strip.status !== 0) {
    step('  (signtool not available - continuing, the copy is usually unsigned anyway)');
  }
} else if (process.platform === 'darwin') {
  spawnSync('codesign', ['--remove-signature', exePath], { encoding: 'utf8' });
}

// --- 5. inject --------------------------------------------------------------

step('Injecting the application...');
const injectArgs = [
  'postject',
  exePath,
  'NODE_SEA_BLOB',
  path.join(BUILD, 'sea-prep.blob'),
  '--sentinel-fuse', 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
];
if (process.platform === 'darwin') {
  injectArgs.push('--macho-segment-name', 'NODE_SEA');
}
// npx is a shell script / .cmd wrapper, so this one genuinely needs a shell.
run('npx', ['--yes', ...injectArgs], { shell: true });

// --- 5b. re-sign and mark executable (macOS) --------------------------------

if (process.platform === 'darwin') {
  step('Re-signing...');
  // Apple Silicon will not execute an arm64 binary with a broken signature at
  // all -- it is killed on launch rather than merely warned about. An ad-hoc
  // signature ("-") satisfies that requirement without a developer account.
  // Gatekeeper still shows its unidentified-developer prompt on first run;
  // that needs real notarisation, which needs a paid Apple Developer ID.
  const sign = spawnSync('codesign', ['--sign', '-', '--force', exePath], {
    encoding: 'utf8',
  });
  if (sign.status !== 0) {
    fail('codesign failed:\n' + (sign.stderr || '').trim());
  }
  fs.chmodSync(exePath, 0o755);
}

// --- 5c. wrap in a .app bundle (macOS) --------------------------------------

// A bare Unix executable cannot be launched from Finder by double-clicking --
// macOS either opens it in a text editor or refuses outright. Wrapping it in a
// minimal .app bundle is what makes it behave like an application.
let appBundlePath = null;
if (process.platform === 'darwin') {
  step('Creating the app bundle...');
  appBundlePath = path.join(DIST, 'Video Converter.app');
  fs.rmSync(appBundlePath, { recursive: true, force: true });

  const macOsDir = path.join(appBundlePath, 'Contents', 'MacOS');
  fs.mkdirSync(macOsDir, { recursive: true });

  fs.writeFileSync(
    path.join(appBundlePath, 'Contents', 'Info.plist'),
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Video Converter</string>
  <key>CFBundleDisplayName</key><string>Video Converter</string>
  <key>CFBundleIdentifier</key><string>local.videoconverter</string>
  <key>CFBundleVersion</key><string>1.0.0</string>
  <key>CFBundleShortVersionString</key><string>1.0.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launch</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict>
</plist>
`
  );

  fs.copyFileSync(exePath, path.join(macOsDir, exeName));
  fs.chmodSync(path.join(macOsDir, exeName), 0o755);

  // The bundle's entry point is a shell script rather than the binary itself,
  // for two reasons. It puts input/ and output/ next to the .app instead of
  // burying them inside Contents/MacOS where nobody would find them, and it
  // re-launches through Terminal: an app started from Finder has no visible
  // console, so the user would see no progress and have no window to close in
  // order to quit. Going through Terminal makes the Mac behave like Windows.
  const launcher = path.join(macOsDir, 'launch');
  fs.writeFileSync(
    launcher,
    `#!/bin/sh
here="$(cd "$(dirname "$0")" && pwd)"
# Contents/MacOS -> Contents -> Bundle.app -> the folder holding the bundle
outer="$(cd "$here/../../.." && pwd)"
exe="$here/${exeName}"

# Already attached to a terminal (someone ran this from a shell): just go.
if [ -t 1 ]; then
  cd "$outer" || exit 1
  exec "$exe"
fi

# Otherwise hand off to Terminal so there is something to watch and close.
# The quoting is deliberate: the path may contain spaces, and AppleScript
# needs embedded double quotes escaped for the shell it eventually runs.
escaped_dir=$(printf '%s' "$outer" | sed 's/"/\\\\"/g')
escaped_exe=$(printf '%s' "$exe" | sed 's/"/\\\\"/g')
osascript \\
  -e 'tell application "Terminal"' \\
  -e "do script \\"cd \\\\\\"$escaped_dir\\\\\\" && \\\\\\"$escaped_exe\\\\\\"\\"" \\
  -e 'activate' \\
  -e 'end tell' >/dev/null 2>&1
`
  );
  fs.chmodSync(launcher, 0o755);

  // Sign the bundle as a whole; signing only the inner binary leaves the
  // bundle itself unsigned and Gatekeeper rejects it on Apple Silicon.
  const signApp = spawnSync('codesign', ['--sign', '-', '--force', '--deep', appBundlePath], {
    encoding: 'utf8',
  });
  if (signApp.status !== 0) {
    fail('codesign of the bundle failed:\n' + (signApp.stderr || '').trim());
  }
}

// --- 6. finish --------------------------------------------------------------

fs.rmSync(BUILD, { recursive: true, force: true });

const sizeMb = (fs.statSync(exePath).size / 1024 / 1024).toFixed(0);
console.log('\nDone.\n');
if (appBundlePath) {
  console.log('  ' + appBundlePath + '  (' + sizeMb + ' MB)');
  console.log('  ' + exePath + '  (the same app, for running from a terminal)');
  console.log('');
  console.log('  Ship the .app. On first run it downloads ffmpeg into a bin');
  console.log('  folder beside itself, then creates output/.');

  // Report what the finished binary actually supports rather than assuming, so
  // a universal build can be told apart from an architecture-specific one.
  const described = spawnSync('file', ['-b', exePath], { encoding: 'utf8' });
  const info = (described.stdout || '').trim();
  const universal = /universal binary/i.test(info);

  console.log('');
  if (universal) {
    console.log('  Architecture: universal - runs natively on Apple Silicon and Intel.');
  } else if (/arm64/.test(info) || process.arch === 'arm64') {
    console.log('  WARNING  This build is Apple Silicon only. It will NOT launch on');
    console.log('           an Intel Mac. To cover both, either:');
    console.log('             npm run build -- --universal    (needs an x64 Node too)');
    console.log('             arch -x86_64 npm run build      (x64 build, runs everywhere)');
  } else {
    console.log('  Architecture: Intel - also runs on Apple Silicon through Rosetta 2.');
  }
} else {
  console.log('  ' + exePath + '  (' + sizeMb + ' MB)');
  console.log('');
  console.log('  Ship that single file. On first run it downloads ffmpeg into a');
  console.log('  bin folder beside itself, then creates output/.');
}
console.log('');
